## The objective of the following python code is to find the spin configuration which has the minimum energy

### First of all we ned to import the useful python libraries

In [2]:
import numpy as  np
import random

### Now, we need to define the spin vector as follows,

In [3]:
spin=[-1,1]

### The size of the 2-D lattice is define by it's length "L"; assuming that it is a square lattice,
### And then we difined a 2-D array "u" which has  L$\times$ L lattice points, each has a spin value (i.e either -1 or +1) 

In [4]:
L=10
u=[[random.choice(spin) for i in range(0,L)] for j in range(0,L)]

### The result can be given as  follows,

In [5]:
u

[[-1, 1, -1, 1, -1, 1, -1, -1, -1, 1],
 [1, 1, 1, 1, 1, -1, 1, 1, -1, -1],
 [-1, -1, -1, -1, 1, 1, 1, 1, -1, 1],
 [-1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
 [1, 1, 1, -1, -1, 1, -1, 1, 1, 1],
 [1, -1, 1, -1, -1, 1, -1, 1, 1, -1],
 [-1, -1, -1, -1, 1, -1, 1, -1, 1, -1],
 [-1, 1, -1, -1, -1, 1, 1, -1, -1, 1],
 [1, 1, -1, 1, 1, 1, 1, -1, -1, 1],
 [1, 1, 1, 1, 1, 1, 1, -1, 1, -1]]

### Now, there is an issue : we haven't considered the boundary conditions. 
### So, we imposed the "periodic boundary conditions" by defining a function called "periodicspin(s)" as follows,

In [6]:
def periodicspin(s):
    for n in range(0,L):
        s[n][L-1]=s[n][0]
        s[L-1][n]=s[0][n]
    return s    


### Let's define the Hamiltonian,

In [7]:
def H(s):
    h=0
    for i in range(0,L-1):
        for j in range(0,L-1):
            #h=h-(s[i][j])*(s[i+1][j]+s[i][j+1])
            h=h-(s[i][j])*(1+ s[i+1][j]+s[i][j+1])
            # Ferromagnet for +
            # Anti ferromagnet for -
            
    return h 

### Main program
#### Using two "for" loops , we can sweep through the all lattice points.
#### First, we calculate the current Energy of the lattice points using the Hamiltonian and assigned into "Haux", Then we select a spin value randomely among the two possibilities for the particular entry; which is "Saux". Before replacing it, we save the existing value as "temp". Now, we can assign the new value "Saux" to the lattice location u [ i ] [ j ] and can calculate the Total enegy. Comparing the Energy of the previous and updated lattice point we can determine whether we are going to update that point or not with the new random spin.

In [8]:
for NN in range(0,10):
    
    for i in range(0,L):
        for j in range(0,L):
            #t=[]
            Haux=H(periodicspin(u))
            Saux=random.choice(spin)
            temp=u[i][j]
            u[i][j]=Saux
            
            if H(periodicspin(u))>=Haux:
                u[i][j]=temp
                
            U=periodicspin(u)

#### Let's check the total energy of the last configuration

In [9]:
print H(periodicspin(U))    

-243


#### Let's display the last configuration

In [10]:
print np.matrix(U)  

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
