In [2]:
import numpy as np
import pylab as py
import matplotlib.pyplot as plt
%matplotlib inline

# Conditionals and Loops - 2


# sums  vs. "vectorizing"

In [3]:
def func_name(input_val):    # a function calculating sum_i=0..9 i^input_val 
    result = 0
    x = np.arange(0,10,1)
    for idx in range(10):
        result += x[idx]**input_val
    return result

out_val = func_name(2)   # call the function
print(out_val)    # print reusult

285


a quicker way to do the same: "vectorizing"

In [4]:
def func_name(input_val):    # a function calculating sum_i=0..9 i^input_val 
    x = np.arange(0,10,1)
    y = (x**input_val).sum()  # first exponentiates the whole numpy array x, then sums it selements
    return y

out_val = func_name(2)   # call the function
print(out_val)    # print reusult

285


# Maps

In [5]:
def func_name(some_number):
    return some_number**2

array_name = np.arange(0,10,1)
print array_name   # Note: this is a numpy array

mymap = map(func_name,array_name)   # this runs the function across a set of data one at a time
                                    
print mymap # Note: the result of each function call is returned in a list...

myarray = np.asarray(mymap)  # ...but we can transform it into a numpy array
print myarray

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [30]:
# now, numpy can also sum over lists...
print mymap
print np.sum(mymap)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
285


In [29]:
# ... as well as numpy arrays
print myarray
print np.sum(myarray)

[ 0  1  4  9 16 25 36 49 64 81]
285


In [34]:
# but we can also do it this way:
print myarray.sum()

285


In [35]:
# ... BUT not with a list
print mymap.sum()

AttributeError: 'list' object has no attribute 'sum'

# Least square fitting

x = (1,2,3,4,...)    # independent variable

yexp = (10, 13, 9,...)   # experimental measurements, supposed to follow  y = a + b*x

chi^2 = sum of squared differences between yexp[i] and y(x[i])

minimize chi^2 w.r.t. a and b gives the "best fit"

d(chi^2)/da = 0 
d(chi^2)/db = 0

solving this system gives minimum of chi^2:
    
    b = sum_1=1..N (x[i]*y[i]) - Sum_i=1..N x[i] * Sum_i=1..N ..........................



